### ISSUE TITLE
🐀 

### ISSUE THREAD

**Issue by oAaronn** [Konstas1312/Discord-Token-Generator#12]
🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀  look at the first line

**Comment by oAaronn** [comment]
🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀

**Comment by oAaronn** [comment]
🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀 🐀

**Comment by Vamp999** [comment]
LOL
